package com.arc8coder.crossword.words

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import com.arc8coder.crossword.R

@Composable
fun words(): Map<String, String>{
    return mapOf(
        stringResource(R.string.abacus) to stringResource(R.string.abacus_def),
        stringResource(R.string.downtime) to stringResource(R.string.downtime_def),
        stringResource(R.string.download) to stringResource(R.string.download_def),
        stringResource(R.string.adware) to stringResource(R.string.adware_def),
        stringResource(R.string.active) to stringResource(R.string.active_def),
        stringResource(R.string.analog) to stringResource(R.string.analog_def),
        stringResource(R.string.amber) to stringResource(R.string.amber_def),
        stringResource(R.string.gutter) to stringResource(R.string.gutter_def),
        stringResource(R.string.graphic) to stringResource(R.string.graphic_def),
        stringResource(R.string.head) to stringResource(R.string.head_def),
        stringResource(R.string.header) to stringResource(R.string.header_def),
        stringResource(R.string.hardware) to stringResource(R.string.hardware_def),
        stringResource(R.string.hertz) to stringResource(R.string.hertz_def),
        stringResource(R.string.heap) to stringResource(R.string.heap_def),
        stringResource(R.string.headphones) to stringResource(R.string.headphones_def),
        stringResource(R.string.hosting) to stringResource(R.string.hosting_def),
        stringResource(R.string.highlight) to stringResource(R.string.highlight_def),
        stringResource(R.string.history) to stringResource(R.string.history_def),
        stringResource(R.string.hologram) to stringResource(R.string.hologram_def),
        stringResource(R.string.home) to stringResource(R.string.home_def),
        stringResource(R.string.hotlink) to stringResource(R.string.hotlink_def),
        stringResource(R.string.hyperlink) to stringResource(R.string.hyperlink_def),
        stringResource(R.string.hypertext) to stringResource(R.string.hypertext_def),
        stringResource(R.string.icon) to stringResource(R.string.icon_def),
        stringResource(R.string.identifier) to stringResource(R.string.identifier_def),
        stringResource(R.string.ignore) to stringResource(R.string.ignore_def),
        stringResource(R.string.image) to stringResource(R.string.image_def),
        stringResource(R.string.guestbook_) to stringResource(R.string.guestbook_def),
        stringResource(R.string.initialization_) to stringResource(R.string.initialization_def),
        stringResource(R.string.initialize) to stringResource(R.string.initialize_def),
        stringResource(R.string.infrared) to stringResource(R.string.infrared_def),
        stringResource(R.string.information) to stringResource(R.string.information_def),
        stringResource(R.string.index) to stringResource(R.string.index_def),
        stringResource(R.string.inbox) to stringResource(R.string.inbox_def),
        stringResource(R.string.import_) to stringResource(R.string.import__def),
        stringResource(R.string.install) to stringResource(R.string.install_def),
        stringResource(R.string.insert) to stringResource(R.string.insert_def),
        stringResource(R.string.input) to stringResource(R.string.input_def),
        stringResource(R.string.inode) to stringResource(R.string.inode_def),
        stringResource(R.string.instructions) to stringResource(R.string.instructions_def),
        stringResource(R.string.integrated) to stringResource(R.string.integrated_def),
        stringResource(R.string.interactive) to stringResource(R.string.interactive_def),
        stringResource(R.string.invalid) to stringResource(R.string.invalid_def),
        stringResource(R.string.intranet) to stringResource(R.string.intranet_def),
        stringResource(R.string.interrupt) to stringResource(R.string.interrupt_def),
        stringResource(R.string.interface_) to stringResource(R.string.interface__def),
        stringResource(R.string.iterator) to stringResource(R.string.iterator_def),
        stringResource(R.string.jiffy) to stringResource(R.string.jiffy_def),
        stringResource(R.string.job) to stringResource(R.string.job_def),
        stringResource(R.string.iphone) to stringResource(R.string.iphone_def),
        stringResource(R.string.joule) to stringResource(R.string.joule_def),
        stringResource(R.string.joystick) to stringResource(R.string.joystick_def),
        stringResource(R.string.jukebox) to stringResource(R.string.jukebox_def),
        stringResource(R.string.justify) to stringResource(R.string.justify_def),
        stringResource(R.string.key) to stringResource(R.string.key_def),
        stringResource(R.string.keyboard) to stringResource(R.string.keyboard_def),
        stringResource(R.string.keylogger) to stringResource(R.string.keylogger_def),
        stringResource(R.string.kilohertz) to stringResource(R.string.kilohertz_def),
        stringResource(R.string.jumper) to stringResource(R.string.jumper_def),
        stringResource(R.string.label) to stringResource(R.string.label_def),
        stringResource(R.string.launch) to stringResource(R.string.launch_def),
        stringResource(R.string.layout) to stringResource(R.string.layout_def),
        stringResource(R.string.language) to stringResource(R.string.language_def),
        stringResource(R.string.lexicon) to stringResource(R.string.lexicon_def),
        stringResource(R.string.library) to stringResource(R.string.library_def),
        stringResource(R.string.linefeed) to stringResource(R.string.linefeed_def),
        stringResource(R.string.legend) to stringResource(R.string.legend_def),
        stringResource(R.string.license) to stringResource(R.string.license_def),
        stringResource(R.string.laser) to stringResource(R.string.laser_def),
        stringResource(R.string.liveware) to stringResource(R.string.liveware_def),
        stringResource(R.string.load) to stringResource(R.string.load_def),
        stringResource(R.string.loader) to stringResource(R.string.loader_def),
        stringResource(R.string.lock) to stringResource(R.string.lock_def),
        stringResource(R.string.location) to stringResource(R.string.location_def),
        stringResource(R.string.login) to stringResource(R.string.login_def),
        stringResource(R.string.lockout) to stringResource(R.string.lockout_def),
        stringResource(R.string.log) to stringResource(R.string.log_def),
        stringResource(R.string.loop) to stringResource(R.string.loop_def),
        stringResource(R.string.loopback) to stringResource(R.string.loopback_def),
        stringResource(R.string.mailbox) to stringResource(R.string.mailbox_def),
        stringResource(R.string.make) to stringResource(R.string.make_def),
        stringResource(R.string.mainframe) to stringResource(R.string.mainframe_def),
        stringResource(R.string.makefile) to stringResource(R.string.makefile_def),
        stringResource(R.string.manual) to stringResource(R.string.manual_def),
        stringResource(R.string.margin) to stringResource(R.string.margin_def),
        stringResource(R.string.page) to stringResource(R.string.page_def),
        stringResource(R.string.palette) to stringResource(R.string.palette_def),
        stringResource(R.string.paddle) to stringResource(R.string.paddle_def),
        stringResource(R.string.paste) to stringResource(R.string.paste_def),
        stringResource(R.string.patch) to stringResource(R.string.patch_def),
        stringResource(R.string.parse) to stringResource(R.string.parse_def),
        stringResource(R.string.pascal) to stringResource(R.string.pascal_def),
        stringResource(R.string.panic) to stringResource(R.string.panic_def),
        stringResource(R.string.petabyte) to stringResource(R.string.petabyte_def),
        stringResource(R.string.phishing) to stringResource(R.string.phishing_def),
        stringResource(R.string.pentium) to stringResource(R.string.pentium_def),
        stringResource(R.string.peripheral) to stringResource(R.string.peripheral_def),
        stringResource(R.string.platform) to stringResource(R.string.platform_def),
        stringResource(R.string.platen) to stringResource(R.string.platen_def),
    )
}